name: dimension-eco-coach
services:
  postgres:
    image: postgres:17
    container_name: postgres-eco-coach
    volumes:
      - postgres-data-eco-coach:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-eco-coach
    volumes:
      - qdrant-data-eco-coach:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
  redis:
    image: redis:latest
    container_name: redis-eco-coach
    ports:
      - "6379:6379"
    volumes:
      - redis-data-eco-coach:/data
    command: redis-server --appendonly yes

volumes:
  qdrant-data-eco-coach:
  postgres-data-eco-coach:
  redis-data-eco-coach:
